### ISSUE TITLE
Import error with AWS Lambda

### ISSUE THREAD

**Issue by neilmcguigan** [frictionlessdata/goodtables-py#323] opened 2020-01-24 06:06 UTC
# Overview

Created a very simple lambda handler that only imports goodtables. Works fine in Pycharm. Created a zip with the pip packages in root, as well as my lambda function. Get the following error:

{
  "errorMessage": "Unable to import module 'lambda_function': cannot import name '_cchardet' from partially initialized module 'cchardet' (most likely due to a circular import) (/var/task/cchardet/__init__.py)",
  "errorType": "Runtime.ImportModuleError"
}

Other lambdas with imported pip modules work just fine

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment] 2020-01-27 15:47
@neilmcguigan 
It seems the problem is related to `cchardet` (which TBH was a source of other installation problems earlier because it's a C-binding)

Some related errors - https://www.google.com/search?q=import+error+with+AWS+Lambda+cchardet&oq=import+error+with+AWS+Lambda+cchardet&aqs=chrome..69i57j33.2909j0j7&sourceid=chrome&ie=UTF-8

**Comment by roll** [comment] 2020-04-24 07:01
It must be fixed now as `tabulator@1.38` uses `chardet` by default - https://github.com/frictionlessdata/tabulator-py#v138

cc @mcarans just FYI regarding the move from `cchardet` by default (the same was for some MacOs, Anaconda etc)

**Closed by roll** 2020-04-24 07:01 UTC
Labels: bug
