### ISSUE TITLE
goodtables datetime issue

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/goodtables-py#173] opened 2017-02-18 00:53 UTC
Running `goodtables datapackage datapackage.json` against column with type `datetime` yields causes incorrect error.  I explicitly set a format for column 5 as `%Y-%m-%d %H:%M:%S` and it still doesn't work.

```
[2,5] [non-castable-value] Row 2 has non castable value 2014-03-06 12:45:29 in column 5 (type: datetime, format: %Y-%m-%d %H:%M:%S)
[2,6] [non-castable-value] Row 2 has non castable value 2014-06-29 07:13:19 in column 6 (type: datetime, format: default)
```

```
>>> from datetime import datetime
>>> datetime_object = datetime.strptime("2014-03-06 12:45:29", "%Y-%m-%d %H:%M:%S")
>>> 
```

**Comment by pwalsh** [comment] 2017-05-23 06:19
@roll do you know the cause of this issue?

**Comment by roll** [comment] 2017-05-23 13:26
@pwalsh 
@danfowler 
I think that's because on Feb18 an actual `jsontableschema` implementation required `fmt:%Y-%m-%d %H:%M:%S`. I have to dive deeper if there is a data package link available.

**Comment by roll** [comment] 2017-05-24 06:52
@danfowler 
closing for now - `goodtables-py` seems doing correct in this situation. And the reason of the error is `specs-prev1/v1`

**Closed by roll** 2017-05-24 06:52 UTC
Labels: bug, planned

**Comment by danfowler** [comment] 2017-05-24 10:54
@roll you're right.  The datetimes were failing on `default` because they were in the format `2014-03-06 12:45:29` instead of `2014-03-06T12:45:29Z` and failing with the `format` because it wasn't prepended with `fmt:`.
