### ISSUE TITLE
ModuleNotFoundError - No module named pyrsistent

### ISSUE THREAD

**Issue by AleksandrMoiseev** [frictionlessdata/goodtables-py#297] opened 2019-05-14 15:53 UTC
Dear colleagues,
Could you please help to install goodtables on AWS EC2 instance.
I have installed Python 3.6.8.
I created virtual environment using " $ python3 -m virtualenv v-env" and activated it with "$ source v-env/bin/activate".
I installed goodtables using "$ pip install --no-cache-dir goodtables"
Then python script with only one line "from goodtables import validate, check, Error" has been executed. And I have got an error "ModuleNotFoundError: No module named 'pyrsistent'"
Could you please help to resolve this issue.
Please find enclosed files:
Version of EC2 instance: [EC2.txt](https://github.com/frictionlessdata/goodtables-py/files/3178686/EC2.txt)
Goodtables install log: [install.txt](https://github.com/frictionlessdata/goodtables-py/files/3178687/install.txt)
Test Python script: [test.py](https://github.com/frictionlessdata/goodtables-py/files/3178692/test.py.txt)

I look forward to hearing from you!
Thank you in advance!

Kind regards,
Alexander MOISEEV

P.S.
The same scenario works fine on Win10 laptop.

**Comment by roll** [comment] 2019-06-03 12:08
Hi @AleksandrMoiseev, I think something wrong with virtualenv on the AWS instance. Have you tried to install it system-wide?

**Comment by roll** [comment] 2019-08-20 11:38
Closing, for now, as I'm not able to reproduce it. Please re-open if there are new information

**Closed by roll** 2019-08-20 11:38 UTC
Labels: question
